# Generated by Django 4.0.6 on 2022-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, help_text='Не более 200 символов', max_length=200, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Полное описание')),
                ('lat', models.FloatField(blank=True, verbose_name='Положение по широте')),
                ('lng', models.FloatField(verbose_name='Положение по долготе')),
            ],
        ),
    ]
