# Generated by Django 4.0.6 on 2022-07-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='index',
            field=models.SmallIntegerField(verbose_name='Порядковый номер'),
        ),
    ]
