# Generated by Django 4.0.6 on 2022-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
