# Generated by Django 4.0.6 on 2022-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.TextField(help_text='Не более 200 символов', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
